- name: Checking if Agent is running
  command: ambari-agent status
  register: result
  ignore_errors: True

- name: Stop Ambari Agent
  shell: ambari-agent stop
  when: result|succeeded

- name: Uninstall Ambari Agent
  yum:
    name: ambari-agent
    state: removed
    disable_gpg_check: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Remove Ambari repository
  yum_repository:
    name: ambari
    state: absent
